sudo: false

language: python

matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      language: generic

install:
  - ./.travis/setup.sh

script:
  - ./.travis/test.sh
